---
name: learn-perl6
cro: 1
id: learn-perl6
env:  []
links:  []
entrypoint: service.p6
endpoints: 
  - 
    port-env: LEARN_PERL6_PORT
    name: HTTP
    protocol: http
    host-env: LEARN_PERL6_HOST
    id: http
...
